#!/usr/bin/env bash

enable -f ./TEMPLATE TEMPLATE
source TEMPLATE_sources.d/TEMPLATE_exit_on_error

clear_screen() { echo $'\e[2J\e[1;1H'; }
key_to_continue() { read -n1 -p Press\ any\ key\ to\ continue; }

TEMPLATE help
key_to_continue
clear_screen

TEMPLATE declare HNAME "bogus string"
TEMPLATE_exit_on_error
echo "Successfully declared TEMPLATE handle HNAME."

