.TH bashbi_vars 7 2025-12-8
.de format_line
.  EX
\fB\\$1\fP\fR\\$2\fP\fI\\$3\fP\fR\\$4\fP
.  EE
..
.SH NAME
.PP
.B bashbi_vars
\- Working with Bash variables

.so bashbi_vars.7.d/description.7
.so bashbi_vars.7.d/definition.7
.so bashbi_vars.7.d/attributes.7



.SH OTHER MACROS
.TP
.B Casting Macros
These macros cast the
.B value
member of the 
.B SHELL_V
