.TH bashbi 7 2025-12-06
.SH NAME
.B bashbi
\- bash_builtin project coding guide
.SH DESCRIPTION
.PP
This page uses an easy-to-remember name to serve as a directory
to related man pages that support development of Bash builtins.
.SH TOPICS
.PP
The page names and descriptions below have been changing as I try
to find an organizing principle.  Don't be afraid to use the
materials, but be prepared for misalignment of topics and content.
.TP
.BR bashbi_vars (7)
Structure of
.B SHELL_VAR
from
.IR variables.h ,
along with a summary of important variable manipulation
functions.
.TP
.BR bashbi_examples (7)
A quick guide to prototypes and usage of a selection of fundamental
Bash internal functions.  This includes a
.B SYNOPSIS
section of prototypes and a set of examples that illustrate their
use.
.TP
.BR bashbi_internals (7)
A discussion of Bash resources that can be called from the
C code of a Bash builtin command.  This includes the steps
needed for calling a script function.
