#!/usr/bin/env bash
source mod_common
bi_enable

cat <<EOF
The builtin, ${B}identify_name${X}, attempts to identify the
characteristics of a given Bash entity.  For variables, it should
list the set flags.  Ideally, ${B}identify_name${X} should also be
able to identify a function as a function.

EOF

declare -i int_global=1

external_func() { echo "Bonjour"; }

run_test()
{
    closure_func() { echo "Hi"; }

    declare -i int_name=0
    declare -a array_name=()
    declare -A assoc_name=()
    declare unspecified_name="bogus"

    # I need to figure out how to use a function variable
    # declare -f func_var=external_func

    echo "${B}Calling to identify several Bash variables${X}"
    identify_name int_global int_name array_name assoc_name unspecified_name test_write_array

    echo "${B}Calling to identify a few Bash functions${X}"
    identify_name external_func, closure_func func_var
}

run_test
