#!/usr/bin/env bash
source mod_common
bi_enable

x_enable "show_attributes"

callout_target()
{
    echo "We got $# arguments, '$*'"
}

callback()
{
    echo "Received a call from 'func_callin' builtin."
    echo "The arguments are: '$*'"

    local callin_name="$1"
    # local -n callout="$2"

    show_attributes callin_name

    printf $'The callin function is \e[32;1m%s\e[m\n' "$callin_name"
    "$callin_name"
    "$callin_name" extra_param
}

echo "About to call 'func_callin'"
func_callin "callback" "callout_target"
