.TH
.SH ATTRIBUTES
.PP
Alongside the
.BR value ,
the
.B attributes
member is the most influential of the
.B SHELL_VAR
object.
It codes data-type as well as the access rules of a given
SHELL_VAR.

.B IMPORTANT:
The attribute settings are a contract, not a guardrail.  There is
nothing to prevent inappropriate access or changes to a SHELL_VAR
in a builtin command.  It is the responsibility of the developer
to understand and conform to the expectations implied by the
.B attributes
value.
.SS ATTRIBUTE RESOURCES
.PP
The header file
.B variables.h
contains resources for interacting with the
.B attributes
member.
.TP
.B Bit Flag Values
The collection of
.B attributes
bit flag macros values are macros with a single bit set to indicate a value.
The first attribute value macro is
.BR att_exported .
.TP
.B Attribute Tests
There are several macros that can be used to test if a given bit
flag value is set.
For example, using
.B exported_p
will detect the the
.B att_exported
bit flag value is set.
.TP
.B Bit Flag Setters
There are several macros that manipulate bits of the
.B attributes
bit field, the most useful of which are
.BR VSETATTR " and " VUNSETATTR .
They both take two arguments,
.BR var " and " attr ,
and set or unset the bit flag value as indicated by
the name.
.IP
.EX
if (invisible_p(sv))
   VUNSETATTR(sv, att_invisible);
.EE
.SS ATTRIBUTE BIT FLAG CATEGORIES
.PP
The following tables group related attribute bit flags:
.PP
.B USER-SETTABLE ATTRIBUTES
.PP
The following attributes are set when the variable is
declared in the script:
.TS
tab(|);
cb s
l l.
Data type bit flags
att_integer|-i
att_array|-a
att_assoc|-A
att_function|-f
att_nameref|-n
.TE
.PP
Data type bit flags are mutually-exclusive.  If no data type
bit flags are set,
.B value
should be treated as a simple character string.
.PP
.TS
tab(|);
cb s
l l lx.
Modified Assignment bit flags
att_lowercase|-u|on assignment, convert string to lowercase
att_uppercase|-u|on assignment, convert string to uppercase
att_capcase|-c|T{
On assignment, lowercase everything except for the first letter
of the first word in the assigned string
T}
att_exported|-x|export variable/function to subshells
att_readonly|-r|cannot change value
att_local||T{
set by using the
.B local
command
T}
att_trace|-t|named function is traced with DEBUG trap
.TE
.PP
.B INTERNAL ATTRIBUTES
.PP
The follwoing attributes are set by the system.  They cannot
be set or read by a Bash script.
.TS
tab(|);
l lx.
att_invisible|cannot see
att_nounset|cannot unset
att_noassign|cannot assign
att_imported|came from environment
att_special|requires special handling
att_nofree|do not free on unset (copied pointer?)
att_regernerate|regenerate when exported
att_tempvar|came from temp environment
att_propagate|propagate to previous scope
.TE
