.TH
.SH ATTRIBUTES
.PP
The
.B attributes
data member is the blueprint of the variable.  It codes
information about the data type, access, and allowed values.
.PP
When a
.B SHELL_VAR is being used in a shell script, the details of the
blueprint are enforced by the runtime environment.  A Bash builtin
.I could
violate every rule in the blueprint.  The developer is responsible
for ensuring the actions of a builtin respect the conditions set out
by the
.B attributes
value.
.SS ATTRIBUTE BIT FLAGS
.PP
The value of each bit flag is a 1 value in a single bit position
of an integer variable.  The
.B attributes
bit flag values are enumerated and named in the header file
.BR variables.h .
.SS ATTRIBUTE RESOURCES
.PP
The
.B variables.h
header file includes macros that enable a developer to recognize
and manage the attribute flags.
.TP
.B Testing Macros
Macros that end with a
.B _p
suffix test for the value of a single flag.  The first example in
.B variables.h
is
.BR exported_p ,
which indicates if the
.B att_exported
flag is set.
.TP
.B Casting Macros
Macros that end with a
.B _cell
cast the
.BR SHELL_VAR :: value
to an approriate pointer for access to the data.
.TP
.B Flag-setting Macros
There are also some flag-setting macros.  The most useful are
.BR VSETATTR " and " VUNSETATTR .
.TP
.B Resources Example
As explained below, it is important to clear the invisible flag
if the
.BR SHELL_VAR :: value
is set or changed:
.IP
.EX
if (invisible_p(sv))
   VUNSETATTR(sv, att_invisible);
.EE
.SS USER-VISIBLE ATTRIBUTES
.PP
This is a class of attribute flags that are set by the user or
developer when declaring the variable.
.TP
.B Data Type Bit Flags
.TS
tab(|);
lb l lx.
att_integer|-i
att_array|-a|collection of values accessed by integer indexes
att_assoc|-A|collection of values accessed by string keys
att_function|-f
att_nameref|-n|indirect access to the named variable
.TE
.TP
.B Data Access Bit Flags
.TS
tab(|);
lb l lx.
att_exported|-x|to be made available to sub-processes
att_readonly|-r|changes prevented in script, prohibited in builtin
att_local||T{
declare with the
.B local
keyword
T}
.TE
.TP
.B Data Constraint Bit Flags
.TS
tab(|);
lb l lx.
att_integer|-i|integer value enforced, but saved as a string
att_lowercase|-l|T{
transform string assignments to all upper-case characters
T}
att_uppercase|-u|T{
transform string assignments to all lower-case characters
T}
att_capcase|-c|T{
transform string assignments to all lower-case EXCEPT the
first character of the first word, which will be upper-case.
T}
.TE
.SS INTERNAL ATTRIBUTES
.PP
This class of attribute flags are set by the Bash runtime
environment to communicate appropriate handling of the variable.
.PP
The notes below that are enclosed in double-quotes have been copied
verbatim from
.BR variables.h .
I haven't explored them sufficiently to confirm my intuititions about
them.
.TE
.TS
tab(|);
lb lx.
att_invisible|T{
This flag is set when a variable is declared in a script but
not assigned a value.  Its value is inaccessible.
.BR IMPORTANT :
this flag must be
.B unset
in a Bash builtin if the value is set, or the user or script will
not be able to access it.
T}
att_nounset|\(dqcannot unset\(dq
att_noassign|\(dqassignment not allowed\(dq
att_imported|\(dqcame from environment\(dq
att_special|\(dqrequires special handling\(dq
att_nofree|\(dqdo not free value on unset\(dq
att_regenerate|\(dqregenerate when exported\(dq
att_tempvar|\(dqvariable came from the temp environment\(dq
att_propagate|\(dqpropagate to previous scope\(dq
.TE




