.so fork.tmac
.SH DESCRIPTION
.PP
This is the uncompleted DESCRIPTION section of the manual page.
.PP
Hopefully, the developer will prepare this page.
.SS RETURN INFORMATION
.PP
The
.B TEMPLATE
builtin command sets the exit value
.RB ( \(dq\(Do?\(dq )
when finished.
Success is indicated by an exit value of
.BR 0 ,
non zero exit values indicate some kind of failure.
.PP
After a recognized failure, the
.B TEMPLATE
command will set the
.B TEMPLATE_ERROR
variable with a helpful description.
