.if !(\n[main_page] = 1) .TH
.SH DESCRIPTION
.PP
Bash is a scripting environment, so it has resources for handling
strings, numbers, etc, and these resources can also be used by
developers of Bash builtins to simplify their work.
.PP
Many of the resources are prototyped in the various header files
in
.BR /usr/include/bash ,
and others can be accessed by making prototype of a function
found in the Bash source code.
.SS CAVEAT
.PP
Keep in mind that this is a first draft, and that the information
will be disorganized.  It mainly serves as a record of resources I
have found useful, along with some examples of usage.

